name: Regain
options:
  bundleIdPrefix: com.kataring
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "16.3"

settings:
  base:
    SWIFT_VERSION: "6"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  Regain:
    type: application
    platform: macOS
    sources:
      - Regain
    settings:
      base:
        INFOPLIST_FILE: Regain/Info.plist
        CODE_SIGN_ENTITLEMENTS: Regain/Regain.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.kataring.regain
        INFOPLIST_KEY_LSUIElement: true
        SWIFT_STRICT_CONCURRENCY: complete
    entitlements:
      path: Regain/Regain.entitlements
      properties:
        com.apple.security.app-sandbox: false
